name: 密钥扫描

permissions:
  contents: read
  
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "Dockerfile"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 加固运行器（审计所有出站调用）
      uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
      with:
        egress-policy: audit
    - name: 检出代码
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - name: 密钥扫描
      uses: trufflesecurity/trufflehog@3a11c8393e96981c44aa78d2b67d52d78f9220e0 # main
      with:
        extra_args: --results=verified,unknown
